### ISSUE TITLE
extracting activations is slow

### ISSUE THREAD

**Issue by mschrimpf** [brain-score/candidate_models#5]
need to measure if it's also slow on CUDA.
perhaps, we can parallelize extracting activations and PCA'ing.

**Comment by asbudhkar** [comment]
Hello
Please could you let me know if CUDA is used automatically if GPU is available or we need to do any code changes?
A pytorch example will be very helpful.
It is taking me hours for extracting activations for one layer using public benchmarks. I need to do it for all layers of resnet to select layers. So, speed up is essential for me.

**Comment by mschrimpf** [comment]
If you use e.g. the `PytorchWrapper` it automatically uses cuda if available: https://github.com/brain-score/model-tools/blob/75365b54670d3f6f63dcdf88395c0a07d6b286fc/model_tools/activations/pytorch.py#L17

But since the benchmarks often only present 100s to 1000s of images, running on CPU typically runs in the same speed or even faster since it avoids the transfer of images onto GPU and the transfer of activations from GPU.

If you use the standard layer selection code, it should prerun all layers in the beginning (https://github.com/brain-score/model-tools/blob/75365b54670d3f6f63dcdf88395c0a07d6b286fc/model_tools/brain_transformation/neural.py#L118-L121, then stored via `result_caching`) so that images only have to be run through the layers once.
