### ISSUE TITLE
ERROR: Cannot find key: --model

### ISSUE THREAD

**Issue by piperod** [brain-score/candidate_models#54]
Hi, I am trying to run the minimal example that is in the documentation, but I am facing this error when invoquing candidate_models: 

2020-02-24 15:57:15,230 INFO:__main__:Running candidate_models --model alexnet
ERROR: Cannot find key: --model

Not sure if I am running it correctly. Thanks.

**Comment by mschrimpf** [comment]
Hi, I would guess that you're missing the function argument from `python candidate_models score_model --model alexnet`, i.e. you're missing the `score_model` argument
