### ISSUE TITLE
Cannot install candidate models because of xarray version conflict

### ISSUE THREAD

**Issue by maytusp** [brain-score/candidate_models#71]
I try to install candidate models to test my trained CORnet-S via  pip install "candidate_models @ git+https://github.com/brain-score/candidate_models", but it has an error message below.

ERROR: Cannot install brain-score and candidate-models==0.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    candidate-models 0.1.0 depends on xarray<=0.12
    brainio-base 0.1.0 depends on xarray==0.16.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

I try to install it using different sever with both windows and Linux, and cannot solve the problem.
What should I do?

**Comment by mschrimpf** [comment]
Thank you for this issue -- you are absolutely correct, it should be addressed shortly by https://github.com/brain-score/candidate_models/pull/72
